/**
 * Budget_Tracking_BackEnd.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Label } from './label';

export interface Budget { 
    id?: number;
    amount?: number;
    description?: string;
    label?: Label;
    category?: Category;
    date?: Date;
    createdDate?: Date;
    updatedDate?: Date;
    userId?: number;
    createdById?: number;
    updatedById?: number;
}