/**
 * Budget_Tracking_BackEnd.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterModel { 
    username?: string | null;
    password?: string | null;
    role?: string | null;
}

